- name: using varsfile
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print course details
    ansible.builtin.debug:
      msg: "Trainer is {{ TRAINER }}, current course is {{ TOOL }} and the duration of the course is {{ DURATION }}"
