- name: vars preference
  hosts: local
  connection: local
  vars:
    COURSE: ansible play
  vars_files:
  - course.yaml
  vars_prompt:
  - name: COURSE
    prompt: enter the course name
    private: false

  tasks:
  - name: checking the vars preference
    vars:
      COURSE: ansible task
    ansible.builtin.debug:
      msg: "{{ COURSE }}"    
