- name: vars preference
  hosts: local
  connection: local
  vars:
    GREETING: "hello from play"
  # vars_files:
  # - course.yaml
  # vars_prompt:
  # - name: GREETING
  #   prompt: please enter the GREETING
  #   private: false  
  tasks:
  - name: print the greeting. 
    # vars:
    #   GREETING: "hello from task"
    ansible.builtin.debug:
      msg: "{{ GREETING }}"  
    


    # vars preference
    # command line or args
    # task
    # file
    # prompt
    # play
    # inventry
