- name: datatypes
  hosts: local
  connection: local
  vars:
    time: 120 #this is number
    course: "Devsecops with aws" #this is string
    is_true: true  #this is boolean
    tools:  # this is list[]
    - linux
    - shell
    - ansible
    concepts:
      ci: jenkins
      scripting: "shell, ansible, terraform, python"

  tasks: 
  - name: print course information
    ansible.builtin.debug:
      msg: "course is: {{ course }}, duration is {{ duration }}, is_live?: {{ is_true }}, tools are: {{ tools }},
         concepts are : {{ concepts }}"    