- name: functions
  hosts: local
  connection: local
  vars:
    Names: "Aman,Aisha,Siddiq"
  tasks: 
  - name: checkundefined variables
    ansible.builtin.debug:
      msg: "{{ NAME | default('Aman') }}"


  - name: split the string of names with ","
    
    ansible.builtin.debug:
      msg: "{{ Nmaes | split',' }}"  

  - name: convert dict to list
    vars:
      details:
        trainer: "Siva"
        duration: 120
        live: true
    ansible.builtin.debug: 
      msg: "{{ details | dict2items }}" 

  - name: list to map or dict 
    vars:
      course:
      - { 'key': 'name' , 'value':'siva' }
      - { 'key': 'duration' , 'value':'120hrs' }
      - { 'key': 'live' , 'value':'true' }

    ansible.builtin.debug:
      msg: "{{ course | items2dict }}"
    
  - name: check the ip is valid or not
    vars:
      IP: "192.168.1.0"
    ansible.builtin.debug:
      msg: "{{ IP | ansible.utils.ipaddr }}"    

  - name: change to upper case
    vars:
      NAME: "Aman"   
    ansible.builtin.debug:
      msg: "{{ NAME | upper }}"   

