- name: shellvscommand
  hosts: local
  connection: local
  tasks: 
  - name: using the shell module
    ansible.builtin.shell: 'ls -la > /tmp/sample.txt'
    register: command_output

  - name: print the command_output
    ansible.builtin.debug:
      msg: "{{ command_output }}"  

  - name: using the command module
    ansible.builtin.command: 'ls -la'   
    register: command_output

  - name: print the command_output
    ansible.builtin.debug:
      msg: "{{ command_output }}"  

      