[local]
localhost ansible_user=ec2-user  ansible_password=DevOps321

[frontend]
frontend.shaik.fun


[catalogue]
catalogue.shaik.fun

[local:vars]
COURSE=ansible
TIME=10HRS
TRAINER=Siva
GREETING="hello from inventry"

[all:vars]
COURSE=ansible
TIME=10HRS
TRAINER=Siva
GREETING="hello from inventry"

